namespace Rickten.EventStore;

/// <summary>
/// Well-known metadata keys for trace identity and event correlation.
/// These keys are used by the event store and reaction framework to maintain
/// traceability across command executions, event causation, and correlation flows.
/// </summary>
public static class EventMetadataKeys
{
    /// <summary>
    /// The unique identifier for an individual persisted event.
    /// Generated by the event store on append; stable and queryable after persistence.
    /// Use this as the target of causation references.
    /// Type: Guid (System metadata source)
    /// </summary>
    public const string EventId = "EventId";

    /// <summary>
    /// Correlation identifier for tracking related events across aggregate boundaries.
    /// When provided by the caller, the metadata source is preserved (typically "Client").
    /// When generated by the system (no caller-provided value), metadata source is "System".
    /// Type: Guid
    /// </summary>
    public const string CorrelationId = "CorrelationId";

    /// <summary>
    /// Identifier referencing the EventId of the event that caused this event.
    /// For reactions, this is the EventId of the trigger event.
    /// For direct command execution, this may be caller-provided or omitted.
    /// Type: Guid (Client or System metadata source depending on origin)
    /// </summary>
    public const string CausationId = "CausationId";

    /// <summary>
    /// Batch identifier shared by all events produced by a single command execution.
    /// All events appended together share the same BatchId.
    /// Generated by the event store for each append operation.
    /// Type: Guid (System metadata source)
    /// </summary>
    public const string BatchId = "BatchId";

    /// <summary>
    /// The UTC timestamp when the event was persisted to the event store.
    /// Generated by the event store on append.
    /// Type: DateTime (System metadata source)
    /// </summary>
    public const string Timestamp = "Timestamp";

    /// <summary>
    /// The version number of this event within its stream (1-indexed).
    /// Generated by the event store on append.
    /// Type: long (System metadata source)
    /// </summary>
    public const string StreamVersion = "StreamVersion";
}
