namespace Rickten.EventStore;

/// <summary>
/// Well-known metadata source identifiers.
/// The Source field in EventMetadata distinguishes where metadata originated.
/// </summary>
public static class EventMetadataSource
{
    /// <summary>
    /// Metadata provided by the client application when appending events.
    /// Examples: user-provided CorrelationId, business context, tenant identifier.
    /// </summary>
    public const string Client = "Client";

    /// <summary>
    /// Metadata generated by the event store system during append.
    /// Examples: EventId, BatchId, Timestamp, StreamVersion, system-generated CorrelationId.
    /// </summary>
    public const string System = "System";

    /// <summary>
    /// Metadata generated by application infrastructure (reactions, sagas, etc.).
    /// Examples: CausationId from reactions, workflow step metadata.
    /// </summary>
    public const string Application = "Application";
}
